Program N05FELIPE_AZEVEDO ;

//FEITO POR NOME FELIPE FERNANDES DE AZEVEDO
{TRABALHO 05....
FUP QUE LEIA OS REGISTROS DO ARQUIVO MEGACLA.TXT (NO ANEXO) QUE CONTEM:
01-05 NUMERO DO SORTEIO
06-08 PRIMEIRA DEZENA
09-11 SEGUNDA DEZENA
12-14 TERCEIRA DEZENA
15-17 QUARTA DEZENA
18-20 QUINTA DEZENA
21-23 SEXTA DEZENA
E ANTES DE ENCERRAR MOSTRE
A FREQUENCIA COM QUE CADA NUMERO FOI SORTEADO)
}


USES TARDENOITE;

VAR
  ARQ:TEXT;                      //NOME LOGICO DO ARQUIVO
	FREQ:ARRAY[1..60] OF INTEGER;  //CONTERAH O TOTAL DE VEZES QUE CADA DEZENA FOI SORTEADA
	REG:STRING[23];                //REGISTRO 
	NUS,TOT,A,B,C,ERRO:INTEGER;
	DEZ_STR: STRING[3];
	
BEGIN
	FOR A:= 1 TO 60 DO
		BEGIN
			FREQ[A]:= 0;
		END;		
  ASSIGN(ARQ,'MEGACLA.TXT');
  RESET(ARQ);
  WHILE NOT (EOF(ARQ)) DO
   BEGIN
    A:= A+1;
    READLN(ARQ,REG);
		//DAQUI PARA FRENTE EH COM VOCES
		//TIRAR AS 6 DEZENAS DE REG
    B:= 6;
		FOR C:=1 TO 6 DO
			BEGIN
				DEZ_STR:= COPY(REG, B, 3);
				VAL(DEZ_STR, NUS, ERRO);
				IF (NUS >= 1) AND (NUS <= 60) THEN
					BEGIN
						FREQ[NUS]:= FREQ[NUS] +1;
					END;
		B:= B + 3;				
				
		//transforma string que contem a dezena sorteada em integer
		//incrementa 1, à posição da dezena sorteada no vetor FREQ.
			END;
   END;
	WRITELN('LIDOS =>',A:20);
	WRITELN;
	WRITELN('DEZ FRE    DEZ FRE    DEZ FRE    DEZ FRE    DEZ FRE    DEZ FRE');
  FOR A:=1 TO 10 DO
		//MOSTRA O A(DEZENA) E A FREQ(CONTERAH A FREQUENCIA DAS DEZENAS)
		//A,FREQ[A],A+10,FREQ[A+10],A+20,FREQ[A+20]....ETC  
  	BEGIN  		
			WRITELN(A:2, FREQ[A]:5, '    ',
            A+10:2, FREQ[A+10]:5, '    ',
            A+20:2, FREQ[A+20]:5, '    ',
            A+30:2, FREQ[A+30]:5, '    ',
            A+40:2, FREQ[A+40]:5, '    ',
            A+50:2, FREQ[A+50]:5);
	 	END;
	WRITELN;
  TERMINE;
  CLOSE(ARQ);
End.