Program N09FELIPE_AZEVEDO;
{ Feito por: Felipe Fernandes de Azevedo
  Trabalho 09 }

USES TARDENOITE;

VAR
  ARQIND: FILE OF REGIS;
  ARQVAGA: TEXT;
  REG: REGIS;
  LISTA: VETOR;
  I, K, POSFIX, ER, TOTGERAL: INTEGER;
  CODSTR, QTDSTR: STRING[4];
  LINHA: STRING[60];
  TABVAGAS: ARRAY[1..12] OF INTEGER;
  POSCARGO: ARRAY[1..12] OF INTEGER;
  APROV: ARRAY[1..12] OF INTEGER;
  NOTAFMT: ARRAY[1..6] OF STRING[5];
  SOMAFMT: STRING[5];
  IDSTR: STRING[10];
  NASCINT, IDADE: INTEGER;

BEGIN
  CORTELA(0);
  TEXTCOLOR(15);
  ASSIGN(ARQVAGA, 'VAGAS.TXT');
  ASSIGN(ARQIND , 'CAND.IND');
  RESET(ARQVAGA);
  RESET(ARQIND);

  FOR I := 1 TO 12 DO
	  BEGIN
	    TABVAGAS[I]:= 0;
	    POSCARGO[I]:= 0;
	    APROV[I]:= 0;
	  END;

  WHILE NOT EOF(ARQVAGA) DO
	  BEGIN
	    READLN(ARQVAGA, LINHA);
	    CODSTR:= COPY(LINHA, 1, 2);
	    QTDSTR:= COPY(LINHA, 30, 2);
	    VAL(CODSTR, K, ER);
	    VAL(QTDSTR, POSFIX, ER);
	
	    IF (K >= 1) AND (K <= 12) THEN
	      TABVAGAS[K]:= POSFIX;
	  END;

  TOTGERAL:= 0;
  POSFIX:= 0;

  WHILE NOT EOF(ARQIND) DO
	  BEGIN
	    READ(ARQIND, REG);
	    TOTGERAL:= TOTGERAL + 1;
	    LISTA[TOTGERAL].PF:= POSFIX;
	    FOR I := 1 TO 6 DO
	    BEGIN
	      STR(REG.NOTAS[I]:3, NOTAFMT[I]);
	      WHILE LENGTH(NOTAFMT[I]) < 3 DO
	        INSERT('0', NOTAFMT[I], 1);
	    END;
	
	    STR(REG.SOM:3, SOMAFMT);
	    WHILE LENGTH(SOMAFMT) < 3 DO
	      INSERT('0', SOMAFMT, 1);
	
	    VAL(REG.DATA.ANO + REG.DATA.MES + REG.DATA.DIA, NASCINT, ER);
	    IDADE:= 20260000 - NASCINT;
	
	    STR(IDADE:8, IDSTR);
	    WHILE LENGTH(IDSTR) < 8 DO
	      INSERT('0', IDSTR, 1);
	
	    LISTA[TOTGERAL].CC:= SOMAFMT + NOTAFMT[4] + NOTAFMT[5] + NOTAFMT[3] + NOTAFMT[2] + NOTAFMT[6] + NOTAFMT[1] + IDSTR;
	    POSFIX:= POSFIX + 1;
	  END;

  WRITELN('AGUARDE...');
  ORDEM(LISTA, TOTGERAL);
  SEEK(ARQIND, 0);

  FOR I:= TOTGERAL DOWNTO 1 DO
  BEGIN
    SEEK(ARQIND, LISTA[I].PF);
    READ(ARQIND, REG);
    REG.CLG:= TOTGERAL - I + 1;
    IF (REG.CAR >= 1) AND (REG.CAR <= 12) THEN
	    BEGIN
	      POSCARGO[REG.CAR]:= POSCARGO[REG.CAR] + 1;
	      REG.CLC:= POSCARGO[REG.CAR];
	      IF REG.CLC <= TABVAGAS[REG.CAR] THEN
		      BEGIN
		        REG.CCL:= REG.CAR;
		        APROV[REG.CAR]:= APROV[REG.CAR] + 1;
		      END
	      ELSE
	        REG.CCL:= 0;
	    END
    ELSE
	    BEGIN
	      REG.CLC:= 0;
	      REG.CCL:= 0;
	    END;

    SEEK(ARQIND, LISTA[I].PF);
    WRITE(ARQIND, REG);
  END;

  CLOSE(ARQIND);
  CLOSE(ARQVAGA);
  WRITELN;
  WRITELN('RESULTADO | APROVADOS POR CARGO:');
  WRITELN;

  FOR I := 1 TO 12 DO
    WRITELN('CARGO ', I:2, ' => ', APROV[I], ' CLASSIFICADOS');
  WRITELN;
  WRITELN('TOTAL DE CANDIDATOS: ', TOTGERAL);
  WRITELN;
  TERMINE;
END.
